# -- Deployment mode lets you specify how to deploy Loki.
# There are 3 options:
# - SingleBinary: Loki is deployed as a single binary, useful for small installs typically without HA, up to a few tens of GB/day.
# - SimpleScalable: Loki is deployed as 3 targets: read, write, and backend. Useful for medium installs easier to manage than distributed, up to a about 1TB/day.
# - Distributed: Loki is deployed as individual microservices. The most complicated but most capable, useful for large installs, typically over 1TB/day.
# Note: SimpleScalable and Distributed REQUIRE the use of object storage.

# -- Helm Chart
# - https://github.com/grafana/loki/tree/main/production/helm/loki
# -- Tested with chart version: 6.7.1

deploymentMode: SimpleScalable
loki:
  auth_enabled: true
  server:
    grpc_listen_port: 9095
    http_listen_port: 3100
    http_server_read_timeout: 600s
    http_server_write_timeout: 600s
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage_config:
    boltdb_shipper:
      index_gateway_client:
        server_address: dns+loki-backend-headless.default.svc.cluster.local:9095
    hedging:
      at: 250ms
      max_per_second: 20
      up_to: 3
    tsdb_shipper:
      index_gateway_client:
        server_address: dns+loki-backend-headless.default.svc.cluster.local:9095
  chunk_store_config:
    chunk_cache_config:
      background:
        writeback_buffer: 500000
        writeback_goroutines: 1
        writeback_size_limit: 500MB
      default_validity: 0s
      memcached:
        batch_size: 4
        parallelism: 5
      memcached_client:
        addresses: dnssrvnoa+_memcached-client._tcp.loki-chunks-cache.default.svc
        consistent_hash: true
        max_idle_conns: 72
        timeout: 2000ms
  common:
    compactor_address: 'http://loki-backend:3100'
    path_prefix: /var/loki
    replication_factor: 3
    storage:
      s3:
        access_key_id: enterprise-logs
        bucketnames: chunks
        endpoint: loki-minio.default.svc:9000
        insecure: true
        s3forcepathstyle: true
        secret_access_key: supersecret
  ingester:
    chunk_encoding: snappy
    chunk_target_size: 5242880
    max_chunk_age: 4h
    chunk_idle_period: 45m
  tracing:
    enabled: true
  querier:
    max_concurrent: 4
    query_ingesters_within: 5h
  frontend:
    scheduler_address: ""
    tail_proxy_url: ""
    max_outstanding_per_tenant: 2048
    compress_responses: true
  frontend_worker:
    scheduler_address: ""
  index_gateway:
    mode: simple
  limits_config:
    max_cache_freshness_per_query: 10m
    query_timeout: 300s
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    volume_enabled: true
    max_query_length: 12h
    retention_period: 4h
    ingestion_rate_mb: 8
    ingestion_burst_size_mb: 12
  compactor:
    working_directory: /tmp/retention
    compaction_interval: 10m
    retention_enabled: true
    retention_delete_delay: 2h
    retention_delete_worker_count: 150
    delete_request_store: s3
  memberlist:
    join_members:
    - loki-memberlist
  pattern_ingester:
    enabled: false
  query_range:
    align_queries_with_step: true
    cache_results: true
    results_cache:
      cache:
        background:
          writeback_buffer: 500000
          writeback_goroutines: 1
          writeback_size_limit: 500MB
        default_validity: 12h
        memcached_client:
          addresses: dnssrvnoa+_memcached-client._tcp.loki-results-cache.default.svc
          consistent_hash: true
          timeout: 500ms
          update_interval: 1m
  ruler:
    storage:
      s3:
        bucketnames: ruler
      type: s3

backend:
  replicas: 3
read:
  replicas: 3
write:
  replicas: 3

minio:
  enabled: true
  replicas: 1
  drivesPerNode: 2
  rootUser: enterprise-logs
  rootPassword: supersecret
  buckets:
    - name: chunks
      policy: none
      purge: false
    - name: ruler
      policy: none
      purge: false
    - name: admin
      policy: none
      purge: false
  persistence:
    size: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

memcached:
  image:
    repository: memcached
    tag: 1.6.23-alpine

chunksCache:
  enabled: true
  allocatedMemory: 1024

resultsCache:
  enabled: true
  allocatedMemory: 1024

singleBinary:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
