repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: grafana
    chart: grafana/grafana
    version: 8.4.7
    namespace: default
    needs: [loki]
    values:
      - ./deps/grafana-values.yaml

  - name: loki
    chart: grafana/loki
    version: 6.7.1
    namespace: default
    values:
      - ./values.yaml

  - name: promtail
    chart: grafana/promtail
    version: 6.16.4
    namespace: default
    needs: [loki]
    values:
      - ./deps/promtail-values.yaml
